---
- name: Add Nautobot BGP Autobomous Systems
  networktocode.nautobot.plugin:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: false
    plugin: bgp
    endpoint: autonomous-systems
    identifiers:
      asn: "{{ item.bgp.asn }}"
    attrs:
      description: "{{ item.bgp.description | default('') }}"
      status: Active
    state: present
  loop: "{{ devices }}"
  when: item.bgp is defined

- name: Add Nautobot BGP Routing Instances
  networktocode.nautobot.plugin:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: false
    plugin: bgp
    endpoint: routing-instances
    identifiers:
      device: "{{ item.0.name }}"
    attrs:
      autonomous_system: 
        asn: "{{ item.0.bgp.asn }}"
      router_id: 
        address: "{{ item.1.ipv4_address }}"
      status: Active
    state: present
  loop: "{{ devices | subelements('interfaces', 'skip_missing=True') }}"
  when: item.0.bgp is defined and item.1.name == 'Loopback0' and item.1.ipv4_address is defined
  register: routing_instance_result

- name: Create data_routing.yml from template
  template:
    src: afi_safi.j2
    dest: "./nautobot_data/data_routing.yml"

- include_vars: "./nautobot_data/data_routing.yml"

- name: Assign address families to BGP Routing Instances
  networktocode.nautobot.plugin:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: false
    plugin: bgp
    endpoint: address-families
    identifiers:
      routing_instance: "{{ item.0.id }}"
      afi_safi: "{{ item.1.afi }}"
    attrs:
      extra_attributes: "{{ item.1.extra_attributes | default({}) }}"
    state: present
  loop: "{{ bgp | subelements('afi_safi', skip_missing=True) }}"

- name: Iterate over BGP Peers
  include_tasks: bgp_peers.yml
  loop: "{{ bgp | subelements('bgp_peers', skip_missing=True) }}"